# @package _global_
# CartPole state-only configuration
# No pixels, small model for fast iteration

general:
  use_pixels: false

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 64

train:
  batch_size: 32
  max_train_steps: 30000

  b_start: -5
  b_end: 6
