# CartPole batch size experiment: B=16 (DreamerV3 style)
# Hypothesis: Better gradient quality, may solve faster despite lower throughput

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 256

train:
  batch_size: 16
  sequence_length: 25
  max_train_steps: 1000
  bootstrap_steps: 1000
  actor_warmup_steps: 1000
  num_collectors: 1
