# CartPole state-only with smaller hidden dim
# No pixels = no need for large latent space

general:
  use_pixels: false

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 64  # Small - state is only 4 floats

train:
  batch_size: 32
  sequence_length: 25
  max_train_steps: 30000
  bootstrap_steps: 5000
  actor_warmup_steps: 5000
  num_collectors: 1
  b_start: -5  # Smaller bin range for CartPole's value scale
  b_end: 6     # symexp([-5..5]) ≈ [-147, +147], enough for max ~100 return
