# CartPole batch size experiment: B=32 (balanced)
# Hypothesis: Balance between throughput and gradient quality

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 256

train:
  batch_size: 32
  sequence_length: 25
  max_train_steps: 1000
  bootstrap_steps: 1000
  actor_warmup_steps: 1000
  num_collectors: 1
