# CartPole profiling - d_hidden=256
environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 256

train:
  batch_size: 8
  max_train_steps: 500
  bootstrap_steps: 100
  actor_warmup_steps: 50
