# CartPole batch size experiment: B=128 (high throughput)
# Hypothesis: Higher throughput but may have diminishing gradient returns

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 256

train:
  batch_size: 128
  sequence_length: 25
  max_train_steps: 1000
  bootstrap_steps: 1000
  actor_warmup_steps: 1000
  num_collectors: 1
