# CartPole-v1: Simple debug environment
# 4D observation, 2 actions, easy dynamics

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 64  # Small env, small model

train:
  batch_size: 8
  max_train_steps: 50000
  bootstrap_steps: 10000
  actor_warmup_steps: 1000
  actor_entropy_coef: 0.01  # Higher entropy for exploration
