# CartPole batch size experiment: B=8 (mystery replication attempt)
# Attempting to replicate 01-03_1901 results

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 256

train:
  batch_size: 8
  sequence_length: 25
  max_train_steps: 3000
  bootstrap_steps: 1000
  actor_warmup_steps: 1000
  num_collectors: 1
