# CartPole with pixel observations
# Best practices from profiling experiments (01-03-26)

general:
  use_pixels: true

environment:
  environment_name: CartPole-v1
  n_actions: 2
  n_observations: 4

models:
  d_hidden: 256  # No speed penalty for larger model

train:
  batch_size: 16      # Works well with replay buffer
  sequence_length: 25 # Match typical episode length
  max_train_steps: 50000
  bootstrap_steps: 10000
  actor_warmup_steps: 5000
  num_collectors: 1   # 2 collectors adds overhead without benefit
